export { default as ArrowRight } from "./Icons/ArrowRight";
export { default as EyeOpen } from "./Icons/EyeOpen";
export { default as ArrowTopRight } from "./Icons/ArrowTopRight";
export { default as AddIcon } from "./Icons/AddIcon";
export { default as StrikeIcon } from "./Icons/StrikeIcon";
export { default as ArrowDown } from "./Icons/ArrowDown";
export { default as CloseIcon } from "./Icons/CloseIcon";
export { default as MenuIcon } from "./Icons/MenuIcon";
export { default as StrikesWideIcon } from "./Icons/StrikesWideIcon";
export { default as ChartIcon } from "./Icons/ChartIcon";
export { default as HistoryIcon } from "./Icons/HistoryIcon";
export { default as CompleteIcon } from "./Icons/CompleteIcon";
export { default as CircleIcon } from "./Icons/CircleIcon";
export { default as EyeClose } from "./Icons/EyeClose";
export { default as SearchIcon } from "./Icons/SearchIcon";
export { default as SquaresIcon } from "./Icons/SquaresIcon";
export { default as PenIcon } from "./Icons/PenIcon";

export { default as Svg } from "./Svg";
export type { SvgProps } from "./types";
