export { default as AddIcon } from "./Icons/Add";
export { default as CloseIcon } from "./Icons/Close";
export { default as OpenNewIcon } from "./Icons/OpenNew";
export { default as ArrowLeft } from "./Icons/ArrowLeft";
export { default as BnbIcon } from "./Icons/BnbIcon";
export { default as ChartIcon } from "./Icons/Chart";
export { default as HistoryIcon } from "./Icons/History";
export { default as GreenArrow } from "./Icons/GreenArrow";
export { default as CopyIcon } from "./Icons/Copy";
export { default as SearchIcon } from "./Icons/Search";
export { default as StrikeIcon } from "./Icons/Strikes";
export { default as SquaresIcon } from "./Icons/Squares";
export { default as EyeOpenIcon } from "./Icons/EyeOpen";
export { default as EyeCloseIcon } from "./Icons/EyeClose";
export { default as ArrowIcon } from "./Icons/Arrow";
export { default as ArrowPanel } from "./Icons/ArrowPanel";
export { default as BtnPanel } from "./Icons/BtnPanel";
export { default as PenIcon } from "./Icons/Pen";
export { default as StrikesWideIcon } from "./Icons/StrikesWide";
export { default as LoadIcon } from "./Icons/Load";
export { default as CompleteIcon } from "./Icons/Complete";
export { default as CercleIcon } from "./Icons/Cercle";
export { default as WatchIcon } from "./Icons/Watch";
export { default as PlayIcon } from "./Icons/Play";
export { default as ArrowDownIcon } from "./Icons/ArrowDown";

export { default as Svg } from "./Svg";
export type { SvgProps } from "./types";
